// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Xenko.Rendering;
using SiliconStudio.Xenko.Graphics;
using SiliconStudio.Xenko.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Xenko.Graphics.Buffer;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace XenkoToolkit.Demo.Outline
{
    public static partial class OutlineShaderKeys
    {
        public static readonly ObjectParameterKey<Texture> OutlineTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<Vector2> OutlineTexelSize = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Color4> ColorOne = ParameterKeys.NewValue<Color4>();
        public static readonly ValueParameterKey<Color4> ColorTwo = ParameterKeys.NewValue<Color4>();
        public static readonly ValueParameterKey<Color4> ColorThree = ParameterKeys.NewValue<Color4>();
    }
}
