// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideToolkit.Demo.Outline
{
    public static partial class OutlineShaderKeys
    {
        public static readonly ObjectParameterKey<Texture> OutlineTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<Vector2> OutlineTexelSize = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Color4> ColorOne = ParameterKeys.NewValue<Color4>();
        public static readonly ValueParameterKey<Color4> ColorTwo = ParameterKeys.NewValue<Color4>();
        public static readonly ValueParameterKey<Color4> ColorThree = ParameterKeys.NewValue<Color4>();
    }
}
