//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("XenkoToolkit")]
[assembly: System.Reflection.AssemblyDescription("A Toolkit for the Xenko game engine. Xenko version 2.1.0.3.")]
[assembly: System.Reflection.AssemblyCompany("dfkeenan")]
[assembly: System.Reflection.AssemblyProduct("XenkoToolkit")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2017")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyInformationalVersion("0.1.0.0-alpha")]
[assembly: System.Reflection.AssemblyVersion("0.1.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.1.0")]


